"""empty message

Revision ID: 4a1daf6630f0
Revises: a1b4c9123939
Create Date: 2024-11-22 14:08:53.480799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1daf6630f0'
down_revision = 'a1b4c9123939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Approved2', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('Approved2')

    # ### end Alembic commands ###
