"""empty message

Revision ID: cb45189a912b
Revises: 55a7135ced0c
Create Date: 2024-11-20 18:39:55.563340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb45189a912b'
down_revision = '55a7135ced0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('ID', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Txt', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ImagePath', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Approved', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
