name: CI/CD Backend Pipeline

on:
  workflow_dispatch:

jobs:
  backend-CI-CD:
    runs-on: ubuntu-latest

    env:
      WORKING_DIRECTORY: ./backend
      AZURE_WEBAPP_NAME: lwa-socialmediadrs-be-dev-eun-001
      AZURE_RESOURCE_GROUP: rg-socialmediadrs-dev-eun-001
      MAIL_USERNAME: ${{ vars.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_DEFAULT_SENDER: ${{ vars.MAIL_DEFAULT_SENDER }}
      FLASK_APP: ${{ vars.FLASK_APP }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      FLASK_ENV: ${{ vars.FLASK_ENV }}

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv antenv
          ./antenv/bin/python -m pip install --upgrade pip
          ./antenv/bin/pip install -r requirements.txt
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Archive production build
        run: |
          zip -r backend.zip .
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Azure CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp deploy \
            --resource-group $AZURE_RESOURCE_GROUP \
            --name $AZURE_WEBAPP_NAME \
            --src-path backend.zip \
            --type zip
