name: Terraform Plan Pipeline

on:
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      BACKEND_RESOURCE_GROUP_NAME: ${{ vars.BACKEND_RESOURCE_GROUP_NAME }}
      BACKEND_STORAGE_ACCOUNT_NAME: ${{ vars.BACKEND_STORAGE_ACCOUNT_NAME }}
      BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME: ${{ vars.BACKEND_STORAGE_ACCOUNT_CONTAINER_NAME }}
      TF_BACKEND_KEY: ${{ vars.APPLICATION_NAME }}-${{ vars.ENVIRONMENT_NAME }}
      WORKING_DIRECTORY: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Validate
        run: |
          chmod +x ${{ github.workspace }}/.github/scripts/terraform-with-backend.sh
          ${{ github.workspace }}/.github/scripts/terraform-with-backend.sh validate
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Plan
        run: |
          chmod +x ${{ github.workspace }}/.github/scripts/terraform-with-backend.sh
          ${{ github.workspace }}/.github/scripts/terraform-with-backend.sh plan -var-file="env-${{ vars.ENVIRONMENT_NAME }}.tfvars"
        working-directory: ${{ env.WORKING_DIRECTORY }}
